name: hojre_shop_app
version: 1.0.0+1
publish_to: none
description: Hojre shop application.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  json_annotation: ^4.6.0
  equatable: ^2.0.3
  connectivity_plus: ^2.3.5
  dartz: ^0.10.1
  intl: ^0.17.0
  fluttericon: ^2.0.0
  dio: ^4.0.6
  synchronized: ^3.0.0+2
  get_it: ^7.2.0
  another_xlider: ^1.1.1
  carousel_slider: ^4.1.1
  persian_number_utility: ^1.1.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  pull_to_refresh: ^2.0.0
  flutter_spinkit: ^5.1.0
  share_plus: ^4.0.10
  flutter_rating_bar: ^4.0.1
  focus_detector: ^2.0.1
  freezed_annotation: ^2.0.3
  flutter_breadcrumb: ^1.0.1
  flutter_launcher_icons: ^0.9.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  path: ^1.8.1
  simple_animations: ^4.2.0
  flare_flutter: ^3.0.2
  shared_preferences: ^2.0.15
  package_info_plus: ^1.4.2
  device_info_plus: ^4.0.0
  double_back_to_close_app: ^2.1.0
  image_picker: ^0.8.5+3
  image: ^3.2.0
  extended_image: ^6.2.1
  barcode_scan2: ^4.2.1
  js: ^0.6.4
  file_picker: ^4.6.1
  url_launcher: ^6.1.4
  dotted_border: ^2.0.0+2
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.1
  mockito: ^5.2.0
  build_runner: ^2.2.0
  freezed: ^2.0.5
  json_serializable: ^6.3.1
  connectivity_plus_platform_interface: ^1.2.1
  plugin_platform_interface: ^2.1.2
  hive_generator: ^1.1.3
  
#  flutter pub run flutter_launcher_icons:main
flutter_icons:
  macos: true
  windows: true
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/media/images/hojre_shop_management_logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/media/images/
  
  fonts:
    - family: Vazir Reg
      fonts:
        - asset: assets/fonts/Vazir-Regular-FD.ttf
    - family: Vazir Bold
      fonts:
        - asset: assets/fonts/Vazir-Bold-FD.ttf
    - family: Vazir Light
      fonts:
        - asset: assets/fonts/Vazir-Light-FD.ttf
    - family: Vazir Med
      fonts:
        - asset: assets/fonts/Vazir-Medium-FD.ttf
    - family: Vazir Thin
      fonts:
        - asset: assets/fonts/Vazir-Thin-FD.ttf
